#!/bin/bash

# Script by: K4lil S1mao
# Update in: 22/02/2021

# Menu de agências

menu() {

	clear
	echo 
	echo -n "

                                                        	     +--------------------------------+
+---------------+                                                    |         SCRIPT PING            |
|MUNICÍPIOS     |  			                             |			 	      |
+---------------+----------------------------------------------------+--------------------------------+----------------------------------------------------------------+
1  - Água Branca                  |24 - Oeiras			     |								
2  - Altos                        |25 - Palmeirais		     |								
3  - Amarante                     |26 - Parnaíba                     |
4  - Anísio de Abreu              |27 - Paulistana                   |
5  - Barras                       |28 - Pedro 2                      |
6  - Batalha                      |29 - Picos                        |
7  - Bom Jesus                    |30 - Pio IX                       |
8  - Buriti dos Lopes             |31 - Piracuruca                   |
9  - Campo Maior                  |32 - Piripiri                     |
10 - Canto do Buriti              |33 - Regeneração                  |
11 - Castelo do Piauí             |34 - São João do Piauí            |
12 - Cocal                        |35 - São Miguel do Tapuio         |
13 - Corrente                     |36 - São Pedro do Piauí           |
14 - Elesbão Veloso               |37 - São Raimundo Nonato          |
15 - Esperantina                  |38 - Simões                       |
16 - Floriano                     |39 - Simplício Mendes             |
17 - Gilbués                      |40 - Teresina - Centro            |
17 - Inhuma                       |41 - Teresina - Parque Piauí      |
19 - Jaicós                       |42 - Teresina - Dirceu            |
20 - José de Freitas              |43 - Teresina - Espaço Cidadania  |
21 - Luis Correia                 |44 - União                        |
22 - Luzilândia                   |45 - Uruçui                       |
23 - Miguel Alves                 |46 - Valença do Piauí             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+

==> "
	read opcao

	case $opcao in
	
    1) source ./municipios/agua_branca.sh
       agua_branca
       menu
       ;;
    2) source ./municipios/altos.sh
       altos
       menu
       ;;
    3) source ./municipios/amarante.sh
       amarante
       menu
       ;;
    4) source ./municipios/anisiodeabreu.sh
       anisiodeabreu
       menu
       ;;
    5) source ./municipios/barras.sh
       barras
       menu
       ;;
    6) source ./municipios/batalha.sh
       batalha
       menu
       ;;
    7) source ./municipios/bomjesus.sh
       bomjesus
       menu
       ;;
    8) source ./municipios/buritidoslopes.sh
       buritidoslopes
       menu
       ;;
    9) source ./municipios/campomaior.sh
       campomaior
       menu
       ;;
    10) source ./municipios/cantodoburiti.sh
        cantodoburiti
        menu
        ;;	
 	11) source ./municipios/campomaior.sh
        campomaior
        menu
        ;;




   *) echo "Opção Inválida"
      menu
      ;;
	
	
	
	
	
	
	
	
	
	
	esac
	

}
menu


