#!/bin/bash

# Script by: K4lil S1mao
# Update in: 22/02/2021

# Menu de agências
cidades=(
  "Água Branca|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Oeiras|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Altos|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Palmeirais|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Amarante|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Parnaíba|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Anísio de Abreu|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Paulistana|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Barras|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Pedro|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Batalha|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Picos|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Bom Jesus|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Pio IX|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Buriti dos Lopes|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Piracuruca|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Campo Maior|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Piripiri|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Canto do Buriti|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Regeneração|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Castelo do Piauí|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "São João do Piauí|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Cocal|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "São Miguel do Tapuio|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Corrente|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "São Pedro do Piauí|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Elesbão Veloso|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "São Raimundo Nonato|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Esperantina|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Simões|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Floriano|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Simplício Mendes|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Gilbués|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Teresina - Centro|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Inhuma|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Teresina - Parque Piauí|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Jaicós|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Teresina - Dirceu|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "José de Freitas|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Teresina - Espaço Cidadania|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Luis Correia|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "União|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Luzilândia|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Uruçui|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Miguel Alves|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
  "Valença do Piauí|Agência (8.8.8.8)|Escritório (8.8.4.4)|Subestação (google.com)"
)

function hr() {
  printf -v pad '%*s' $COLUMNS
  pad=$(: "${pad// /-}"; : "${_/#-/+}"; echo "${_/%-/+}")
  echo "$pad"
}

function menu() {
  # Selecionando opção de cidade variável opt
  hr
  column < <(
  for ((i=0;i<${#cidades[@]};i++)); do
    printf '%2s - %s\n' "$i" "${cidades[i]%%|*}"
  done
  printf '%2s - %s\n' "q" "Sair"
  )
  hr
  read -p "==> " i
  [[ $i == 'q' ]] && return 1
  IFS='|' read -a opt <<< "${cidades[i]}"

  # Selecionando subopção de 3 em variável i
  hr
  for((i=1;i<${#opt[@]};i++)); do
    printf '%2s - %s\n' "$i" "${opt[i]}"
  done
  printf '%2s - %s\n' "m" "Menu"
  hr
  read -p "==> " i
  [[ $i == 'm' ]] && return 0

  # Executando comando ping -c3 IP
  printf 'Pinging %s...\n' "${opt[i]}"
  ip="${opt[i]#*\(}"
  if [[ ${ip%)} ]]; then
    ping -c3 "${ip%)}"
  fi
}

while [[ $? == 0 ]]; do
  menu
done
